import { createContext, useContext } from 'react';
import brand from '../../shared/brand.json';

export const LangContext = createContext({ lang: 'en', toggleLang: () => {} });
export const useLang = () => useContext(LangContext);

export const BRAND = {
  ...brand,
  nameShort: 'Guruvandanam',
  logoAlt: brand.org,
};

export const t = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    leaderboard: 'Leaderboard',
    myProgress: 'My Progress',
    rules: 'Rules',
    admin: 'Admin',
    logout: 'Logout',
    // Auth
    signIn: 'Sign In',
    register: 'Register',
    joinChallenge: 'Register for Guruvandanam',
    welcomeBack: 'Welcome back',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    age: 'Age',
    agePlaceholder: 'Your age (6–60)',
    alreadyReg: 'Already registered?',
    newHere: `New to ${BRAND.nameShort}?`,
    registerHere: 'Register here',
    competitionRules: 'Competition Rules',
    adminSignIn: 'Admin Sign In',
    adminOnly: 'This portal is for administrators only',
    backToLogin: '← Back to user login',
    // Dashboard
    guruvandanCounter: 'Guruvandan Counter',
    hello: 'Hello',
    totalGuruvandans: 'Total Guruvandans',
    dayGuruvandans: "Today's Guruvandans",
    guruvandansOn: 'Guruvandans on',
    guruvandansLogged: 'guruvandan added',
    enterCount: 'Enter count',
    progressGoal: 'Progress to 1008 guruvandan',
    markDone: '✓ Mark Done',
    undo: '✕ Undo',
    log: 'Add',
    remove: '✕ Clear',
    daysLeftLabel: 'Days Left',
    perDayLabel: 'Needed / Day',
    perWeekLabel: 'Needed / Week',
    goalAchievedShort: 'Goal Achieved! 🎉',
    // Profile
    myProgressTitle: 'My Progress',
    totalGuruvandansLabel: 'Total Guruvandans',
    remainingLabel: 'Remaining to Goal',
    activeDaysLabel: 'Active Days',
    competitionGoal: 'Competition Goal',
    goalAchieved: '🎉 Goal Achieved!',
    complete: '% complete',
    recentActivity: 'Recent Activity (Last 30 Days)',
    days: 'days',
    // Leaderboard
    leaderboardTitle: '🏆 Leaderboard',
    leaderboardSub: `Top participants in ${BRAND.name} ${BRAND.year}`,
    yourRank: 'Your Rank',
    allGroups: 'All Groups',
    group: 'Group',
    points: 'Guruvandans',
    progress: 'Progress',
    status: 'Status',
    goalMet: 'Goal Met ✓',
    inProgress: 'In Progress',
    name: 'Name',
    // Admin
    adminPanel: 'Admin Panel',
    totalUsers: 'Total Users',
    feePaid: 'Fee Paid',
    feePending: 'Fee Pending',
    goalMetLabel: '1008 Guruvandan Met',
    searchPlaceholder: 'Search by name or email...',
    users: 'users',
    rank: 'Rank',
    emailLabel: 'Email',
    groupLabel: 'Group',
    pointsLabel: 'Guruvandans',
    feeLabel: 'Fee Paid',
    adminLabel: 'Admin',
    joinedLabel: 'Joined',
    paid: '✓ Paid',
    pending: '✕ Pending',
    makeAdmin: 'Make Admin',
    // Groups
    g1label: 'Group 1 (Age 6–15)',
    g2label: 'Group 2 (Age 15–25)',
    g3label: 'Group 3 (Age 26–60)',
    // Lock messages
    dashLocked: `🔒 ${BRAND.name} will start from ${BRAND.competitionStartDisplay}.`,
    readonlyNotice: '🔒 Old date — view only',
    // Disqualified
    disqualifiedBanner: '⚠️ You have been disqualified from this competition. Please contact the organizers for more information.',
    // Phone required
    phoneRequiredTitle: '⚠️ Phone number required',
    phoneRequiredMsg: 'Please add your phone number. You cannot proceed to any other page of the site until your phone number is added.',
    // Misc
    loading: 'Loading...',
    loadingActivities: 'Loading activities...',
  },
  hi: {
    // Nav
    dashboard: 'डैशबोर्ड',
    leaderboard: 'लीडरबोर्ड',
    myProgress: 'मेरी प्रगति',
    rules: 'नियम',
    admin: 'एडमिन',
    logout: 'लॉग आउट',
    // Auth
    signIn: 'साइन इन',
    register: 'पंजीकरण',
    joinChallenge: 'गुरुवंदनम् के लिए पंजीकरण करें',
    welcomeBack: 'वापसी पर स्वागत है',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    password: 'पासवर्ड',
    age: 'आयु',
    agePlaceholder: 'आपकी आयु (6–60)',
    alreadyReg: 'पहले से पंजीकृत हैं?',
    newHere: `${BRAND.nameShort} में नए हैं?`,
    registerHere: 'यहाँ पंजीकरण करें',
    competitionRules: 'प्रतियोगिता नियम',
    adminSignIn: 'एडमिन साइन इन',
    adminOnly: 'यह पोर्टल केवल प्रशासकों के लिए है',
    backToLogin: '← यूज़र लॉगिन पर वापस जाएं',
    // Dashboard
    guruvandanCounter: 'गुरुवंदन काउंटर',
    hello: 'नमस्ते',
    totalGuruvandans: 'कुल गुरुवंदन',
    dayGuruvandans: 'आज के गुरुवंदन',
    guruvandansOn: 'गुरुवंदन तिथि',
    guruvandansLogged: 'गुरुवंदन जोड़े गए',
    enterCount: 'संख्या दर्ज करें',
    progressGoal: '1008 गुरुवंदन की ओर प्रगति',
    markDone: '✓ पूर्ण करें',
    undo: '✕ पूर्ववत करें',
    log: 'जोड़ें',
    remove: '✕ हटाएं',
    daysLeftLabel: 'शेष दिन',
    perDayLabel: 'प्रति दिन आवश्यक',
    perWeekLabel: 'प्रति सप्ताह आवश्यक',
    goalAchievedShort: 'लक्ष्य पूर्ण! 🎉',
    // Profile
    myProgressTitle: 'मेरी प्रगति',
    totalGuruvandansLabel: 'कुल गुरुवंदन',
    remainingLabel: 'लक्ष्य तक शेष',
    activeDaysLabel: 'सक्रिय दिन',
    competitionGoal: 'प्रतियोगिता लक्ष्य',
    goalAchieved: '🎉 लक्ष्य पूर्ण!',
    complete: '% पूर्ण',
    recentActivity: 'हाल की गतिविधि (पिछले 30 दिन)',
    days: 'दिन',
    // Leaderboard
    leaderboardTitle: '🏆 लीडरबोर्ड',
    leaderboardSub: `${BRAND.name} ${BRAND.year} के शीर्ष प्रतिभागी`,
    yourRank: 'आपकी रैंक',
    allGroups: 'सभी समूह',
    group: 'समूह',
    points: 'गुरुवंदन',
    progress: 'प्रगति',
    status: 'स्थिति',
    goalMet: 'लक्ष्य पूर्ण ✓',
    inProgress: 'जारी है',
    name: 'नाम',
    // Admin
    adminPanel: 'एडमिन पैनल',
    totalUsers: 'कुल सदस्य',
    feePaid: 'शुल्क भुगतान',
    feePending: 'शुल्क बकाया',
    goalMetLabel: '1008 गुरुवंदन पूर्ण',
    searchPlaceholder: 'नाम या ईमेल से खोजें...',
    users: 'सदस्य',
    rank: 'रैंक',
    emailLabel: 'ईमेल',
    groupLabel: 'समूह',
    pointsLabel: 'गुरुवंदन',
    feeLabel: 'शुल्क भुगतान',
    adminLabel: 'एडमिन',
    joinedLabel: 'शामिल हुए',
    paid: '✓ भुगतान',
    pending: '✕ बकाया',
    makeAdmin: 'एडमिन बनाएं',
    // Groups
    g1label: 'समूह 1 (आयु 6–15)',
    g2label: 'समूह 2 (आयु 15–25)',
    g3label: 'समूह 3 (आयु 26–60)',
    // Lock messages
    dashLocked: `🔒 ${BRAND.name} ${BRAND.competitionStartDisplay} से शुरू होगा।`,
    readonlyNotice: '🔒 पुरानी तिथि — केवल देखने के लिए',
    // Disqualified
    disqualifiedBanner: '⚠️ आपको इस प्रतियोगिता से अयोग्य घोषित किया गया है। अधिक जानकारी के लिए आयोजकों से संपर्क करें।',
    // Phone required
    phoneRequiredTitle: '⚠️ फ़ोन नंबर आवश्यक है',
    phoneRequiredMsg: 'कृपया अपना फ़ोन नंबर जोड़ें। फ़ोन नंबर जोड़े बिना आप साइट के किसी अन्य पेज पर नहीं जा सकते।',
    // Misc
    loading: 'लोड हो रहा है...',
    loadingActivities: 'गतिविधियां लोड हो रही हैं...',
  },
};
