import { createContext, useContext } from 'react';
import brand from '../../shared/brand.json';

export const LangContext = createContext({ lang: 'en', toggleLang: () => {}, activityLang: 'gu', toggleActivityLang: () => {} });
export const useLang = () => useContext(LangContext);

export const BRAND = {
  ...brand,
  nameShort: 'Guruvandanam',
  logoAlt: brand.org,
  yearGu: '૨૦૨૬',
  competitionStartDisplayGu: '૦૪/૦૮/૨૦૨૬',
};

export const t = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    leaderboard: 'Leaderboard',
    myProgress: 'My Progress',
    rules: 'Rules',
    admin: 'Admin',
    logout: 'Logout',
    // Auth
    signIn: 'Sign In',
    register: 'Register',
    joinChallenge: `${BRAND.nameGu} માટે નોંધણી કરો`,
    welcomeBack: 'Welcome back',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    age: 'Age',
    agePlaceholder: 'Your age (6–60)',
    alreadyReg: 'Already registered?',
    newHere: `New to ${BRAND.nameShort}?`,
    registerHere: 'Register here',
    competitionRules: 'Competition Rules',
    adminSignIn: 'Admin Sign In',
    adminOnly: 'This portal is for administrators only',
    backToLogin: '← Back to user login',
    // Dashboard
    guruvandanCounter: 'Guruvandan Counter',
    hello: 'Hello',
    totalGuruvandans: 'Total Guruvandans',
    dayGuruvandans: "Today's Guruvandans",
    guruvandansOn: 'Guruvandans on',
    guruvandansLogged: 'guruvandans logged',
    enterCount: 'Enter count',
    progressGoal: 'Progress to 1008 goal',
    markDone: '✓ Mark Done',
    undo: '✕ Undo',
    log: 'Add',
    remove: '✕ Clear',
    // Profile
    myProgressTitle: 'My Progress',
    totalGuruvandansLabel: 'Total Guruvandans',
    remainingLabel: 'Remaining to Goal',
    activeDaysLabel: 'Active Days',
    competitionGoal: 'Competition Goal',
    goalAchieved: '🎉 Goal Achieved!',
    complete: '% complete',
    recentActivity: 'Recent Activity (Last 30 Days)',
    days: 'days',
    // Leaderboard
    leaderboardTitle: '🏆 Leaderboard',
    leaderboardSub: `Top participants in ${BRAND.name} ${BRAND.year}`,
    yourRank: 'Your Rank',
    allGroups: 'All Groups',
    group: 'Group',
    points: 'Guruvandans',
    progress: 'Progress',
    status: 'Status',
    goalMet: 'Goal Met ✓',
    inProgress: 'In Progress',
    name: 'Name',
    // Admin
    adminPanel: 'Admin Panel',
    totalUsers: 'Total Users',
    feePaid: 'Fee Paid',
    feePending: 'Fee Pending',
    goalMetLabel: 'Goal Met (1008)',
    searchPlaceholder: 'Search by name or email...',
    users: 'users',
    rank: 'Rank',
    emailLabel: 'Email',
    groupLabel: 'Group',
    pointsLabel: 'Guruvandans',
    feeLabel: 'Fee Paid',
    adminLabel: 'Admin',
    joinedLabel: 'Joined',
    paid: '✓ Paid',
    pending: '✕ Pending',
    makeAdmin: 'Make Admin',
    // Groups
    g1label: 'Group 1 (Age 6–15)',
    g2label: 'Group 2 (Age 15–25)',
    g3label: 'Group 3 (Age 26–60)',
    // Lock messages
    dashLocked: `🔒 ${BRAND.nameGu} તા. ${BRAND.competitionStartDisplay} પછી જ ભરી શકાશે.`,
    // Phone required
    phoneRequiredTitle: '⚠️ Phone number required',
    phoneRequiredMsg: 'Please add your phone number. You cannot proceed to any other page of the site until your phone number is added.',
    // Misc
    loading: 'Loading...',
    loadingActivities: 'Loading activities...',
  },
  gu: {
    // Nav
    dashboard: 'ડૅશબોર્ડ',
    leaderboard: 'ક્રમ સૂચિ',
    myProgress: 'મારી પ્રગતિ',
    rules: 'નિયમો',
    admin: 'એડમિન',
    logout: 'લૉગ આઉટ',
    // Auth
    signIn: 'પ્રવેશ કરો',
    register: 'નોંધણી',
    joinChallenge: 'પડકારમાં જોડાઓ',
    welcomeBack: 'સ્વાગત છે',
    fullName: 'પૂરું નામ',
    email: 'ઈ-મેઈલ',
    password: 'પાસવર્ડ',
    age: 'ઉંમર',
    agePlaceholder: 'ઉંમર (6-60)',
    alreadyReg: 'પહેલેથી નોંધાયેલ?',
    newHere: 'આ પ્રથમ વખત?',
    registerHere: 'અહીં નોંધો',
    competitionRules: 'સ્પર્ધાના નિયમો',
    adminSignIn: 'એડમિન પ્રવેશ',
    adminOnly: 'આ પ્રવેશ ફક્ત સંચાલકો માટે છે',
    backToLogin: '← યુઝર લૉગિન પર પાછા',
    // Dashboard
    guruvandanCounter: 'ગુરુવંદન ગણતરી',
    hello: 'નમસ્કાર',
    totalGuruvandans: 'કુલ ગુરુવંદન',
    dayGuruvandans: 'આજના ગુરુવંદન',
    guruvandansOn: 'ગુરુવંદન તારીખ',
    guruvandansLogged: 'ગુરુવંદન નોંધાયા',
    enterCount: 'સંખ્યા દાખલ કરો',
    progressGoal: '૧૦૦૮ ગુરુવંદન ધ્યેય તરફ',
    markDone: '✓ થઈ ગયું',
    undo: '✕ રદ કરો',
    log: 'ઉમેરો',
    remove: '✕ કાઢો',
    // Profile
    myProgressTitle: 'મારી પ્રગતિ',
    totalGuruvandansLabel: 'કુલ ગુરુવંદન',
    remainingLabel: 'ધ્યેય માટે બાકી',
    activeDaysLabel: 'સક્રિય દિવસો',
    competitionGoal: 'સ્પર્ધા ધ્યેય',
    goalAchieved: '🎉 ધ્યેય પ્રાપ્ત!',
    complete: '% પૂર્ણ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ (છેલ્લા ૩૦ દિવસ)',
    days: 'દિવસ',
    // Leaderboard
    leaderboardTitle: '🏆 ક્રમ સૂચિ',
    leaderboardSub: `${BRAND.nameGu} ${BRAND.yearGu} ના ટોચના સ્પર્ધક`,
    yourRank: 'તમારો ક્રમ',
    allGroups: 'બધા જૂથ',
    group: 'જૂથ',
    points: 'ગુરુવંદન',
    progress: 'પ્રગતિ',
    status: 'સ્થિતિ',
    goalMet: 'ધ્યેય ✓',
    inProgress: 'ચાલુ',
    name: 'નામ',
    // Admin
    adminPanel: 'સંચાલક પેનલ',
    totalUsers: 'કુલ સભ્ય',
    feePaid: 'ફી ભરી',
    feePending: 'ફી બાકી',
    goalMetLabel: 'ધ્યેય (1008)',
    searchPlaceholder: 'નામ અથવા ઈ-મેઈલ શોધો...',
    users: 'સભ્ય',
    rank: 'ક્રમ',
    emailLabel: 'ઈ-મેઈલ',
    groupLabel: 'જૂથ',
    pointsLabel: 'ગુરુવંદન',
    feeLabel: 'ફી ભરી',
    adminLabel: 'એડમિન',
    joinedLabel: 'જોડાયા',
    paid: '✓ ભરી',
    pending: '✕ બાકી',
    makeAdmin: 'એડમિન બનાવો',
    // Groups
    g1label: 'જૂથ ૧ (ઉ. ૬–૧૫)',
    g2label: 'જૂથ ૨ (ઉ. ૧૫–૨૫)',
    g3label: 'જૂથ ૩ (ઉ. ૨૬–૫૦)',
    // Phone required
    phoneRequiredTitle: '⚠️ ફોન નંબર જરૂરી છે',
    phoneRequiredMsg: 'કૃપા કરીને તમારો ફોન નંબર ઉમેરો. ફોન નંબર ઉમેર્યા વગર સાઇટના અન્ય કોઈ પણ પેજ પર જઈ શકાશે નહીં.',
    // Lock messages
    dashLocked: `🔒 ${BRAND.nameGu} તા. ${BRAND.competitionStartDisplay} થી શરૂ થશે. ગુરુવંદન ${BRAND.competitionStartDisplayGu} થી ભરી શકાશે.`,
    // Misc
    loading: 'લોડ થઈ રહ્યું છે...',
    loadingActivities: 'પ્રવૃત્તિઓ લોડ...',
  },
  hi: {
    // Phone required
    phoneRequiredTitle: '⚠️ फ़ोन नंबर आवश्यक है',
    phoneRequiredMsg: 'कृपया अपना फ़ोन नंबर जोड़ें। फ़ोन नंबर जोड़े बिना आप साइट के किसी अन्य पेज पर नहीं जा सकते।',
    dashLocked: `🔒 गुरुवंदनम् ${BRAND.competitionStartDisplay} से शुरू होगा।`,
  },
};
